apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureReadOnlyRootFilesystem
metadata:
  name: psp-readonlyrootfilesystem
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
